---
# tasks file for software
- name: Ensure install packages
  apt:
    update_cache: yes
    pkg:
      - maven
      - git

- name: Ensure upload from git project
  git:
    repo: 'https://github.com/boxfuse/boxfuse-sample-java-war-hello.git'
    dest: /home/ubuntu

- name: Ensure build project
  shell:
    mvn package
  args:
    chdir: /home/ubuntu
