---
# tasks file for web
- name: Ensure install tomcat
  apt:
    update_cache: yes
    name: tomcat9

- name: Ensure transfer .war to build
  synchronize:
    src: /home/ubuntu/target/hello-1.0.war
    dest: /var/lib/tomcat9/webapps/hello-1.0.war
  delegate_to: 178.154.231.164